[Rainmeter]
Update=-1
Author=Connect-R

[Variables]
@include=#@#Variables.inc
@include2=#@#Language\Language.inc

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeterSettingsBg]
Meter=Shape
X=0
Y=40
Shape=Rectangle 1,1,700,400,0 | Fill LinearGradient MyGradient | Extend MyModifiers1
MyModifiers1=Stroke Color 0,0,0,0
MyGradient= -90 | 0,0,0,230 ; 0.15 | 0,0,0,55  ; 0.99

[MeterSettingsBg2]
Meter=Shape
X=0
Y=0
Shape=Rectangle 1,1,700,40 | Fill Color 0,0,0 | Stroke Color 0,0,0,0

[MeterLine]
Meter=Shape
X=400
Y=41
Shape=Rectangle 0,0,0,400 | Fill Color 0,0,0,0 | Stroke Color 255,255,255

[MeterDayBg]
Meter=Shape
X=20
Y=349
Shape=Rectangle 1,1,98,23 | Fill Color 0,0,0,80 | Stroke Color 255,255,255

[MeterMonthBg]
Meter=Shape
X=145
Y=349
Shape=Rectangle 1,1,98,23 | Fill Color 0,0,0,80 | Stroke Color 255,255,255

[MeterYearBg]
Meter=Shape
X=270
Y=349
Shape=Rectangle 1,1,98,23 | Fill Color 0,0,0,80 | Stroke Color 255,255,255

[MeterEventBg]
Meter=Shape
X=20
Y=395
Shape=Rectangle 1,1,350,23 | Fill Color 0,0,0,80 | Stroke Color 255,255,255

[MeterTranslateBg]
Meter=Shape
X=280
Y=95
Shape=Rectangle 1,1,94,20 | Fill Color 0,0,0,80 | Stroke Color 255,255,255

[MeterLocationBg]
Meter=Shape
X=280
Y=170
Shape=Rectangle 1,1,94,20 | Fill Color 0,0,0,80 | Stroke Color 255,255,255

[Meter24hClockBg]
Meter=Shape
X=425
Y=300
Shape=Rectangle 1,1,100,30 | Fill Color 0,0,0,80 | Stroke Color 255,255,255

[Meter12hClockBg]
Meter=Shape
X=555
Y=300
Shape=Rectangle 1,1,100,30 | Fill Color 0,0,0,80 | Stroke Color 255,255,255

[MeterCelsiusBg]
Meter=Shape
X=425
Y=344
Shape=Rectangle 1,1,100,30 | Fill Color 0,0,0,80 | Stroke Color 255,255,255

[MeterFahrenheitBg]
Meter=Shape
X=555
Y=344
Shape=Rectangle 1,1,100,30 | Fill Color 0,0,0,80 | Stroke Color 255,255,255

[MeterCloseBg]
Meter=Shape
X=470
Y=390
Shape=Rectangle 1,1,140,30 | Fill Color 0,0,0,80 | Stroke Color 255,255,255

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeterSettingsText]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontColor=255,255,255
FontSize=15
X=360
Y=6
Text=">  S        E        T        T        I        N        G        S  <"
AntiAlias=1

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeterInstructionText]
Meter=String
StringAlign=Left
FontFace=Segoe UI Light
FontColor=255,255,255
FontSize=12
X=60
Y=95
Text=Translate Instructions    >>>>
AntiAlias=1

[MeterTranslateButton]
Meter=String
StringAlign=Center
FontFace=Segoe UI
FontSize=11
FontColor=255,255,255
X=322
Y=95
Text=Translate
SolidColor=0,0,0,1
AntiAlias=1
LeftMouseUpAction=["#ROOTCONFIGPATH#@Resources\Language\Language.inc"]
ToolTipText=Click here to see how to translate to your language.#CRLF#When you finish, don't forget to save config and refresh Rainmeter!

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeterLocationFind]
Meter=String
StringAlign=Left
FontFace=Segoe UI Light
FontColor=255,255,255
FontSize=12
X=60
Y=130
Text=Find Your Weather Code Here  >>
AntiAlias=1

[MeterLocationCode]
Meter=Image
ImageName=#@#Location.png
X=250r
Y=-6r
W=30
AntiAlias=1
ImageTint=255,255,255
ToolTipText="Find your weather "Location Code" on this site."
LeftMouseDownAction=["https://weather.codes/"]

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeterWeatherCode]
Meter=String
StringAlign=Left
FontColor=255,255,255
FontFace=Segoe UI Light
FontSize=12
X=60
Y=170
Text=Enter Weather Code Here >>
AntiAlias=1

[MeterCode]
Meter=String
StringAlign=Center
FontFace=Segoe UI
FontColor=255,255,255
FontSize=12
X=265r
Y=0r
Text=#Location#
AntiAlias=1
ToolTipText=Type your weather "Location Code" and press the "Enter" key to Apply changes.
LeftMouseUpAction=[!PluginBang "MeterInput ExecuteBatch 1"]

[MeterInput]
Measure=Plugin
Plugin=InputText.dll
StringAlign=Center
FontFace=Segoe UI
FontSize=12
X=280
Y=170
W=95
H=20
AntiAlias=1
FocusDismiss=1
Command1=[!WriteKeyValue Variables Location "$UserInput$""#@#Variables.inc"][!RainmeterRefreshApp]
DefaultValue="#Location#"

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeterTextColor1]
Meter=String
StringAlign=Left
FontColor=255,255,255
FontFace=Segoe UI Light
FontSize=12
X=65
Y=235
Text=Color 1     >>>>>>>>>
AntiAlias=1

[MeterTextColor1a]
Meter=String
StringAlign=Center
FontFace=Segoe UI
FontColor=#Color1#
FontSize=12
X=260r
Y=0r
W=100
Text=#Color1#
AntiAlias=1
SolidColor=0,0,0,80
LeftMouseUpAction=["#@#Addons\RainRGB4.exe" "VarName=Color1" "FileName=#@#Variables.inc"]
FinishAction=[!Refresh *]

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeterTextColor2]
Meter=String
StringAlign=Left
FontColor=255,255,255
FontFace=Segoe UI Light
FontSize=12
X=65
Y=260
Text=Color 2    >>>>>>>>>
AntiAlias=1

[MeterTextColor2a]
Meter=String
StringAlign=Center
FontFace=Segoe UI
FontColor=#Color2#
FontSize=12
X=260r
Y=0r
W=100
Text=#Color2#
AntiAlias=1
SolidColor=0,0,0,80
LeftMouseUpAction=["#@#Addons\RainRGB4.exe" "VarName=Color2" "FileName=#@#Variables.inc"]
FinishAction=[!Refresh *]

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeterTextColor3]
Meter=String
StringAlign=Left
FontColor=255,255,255
FontFace=Segoe UI Light
FontSize=12
X=65
Y=285
Text=Color 3    >>>>>>>>>
AntiAlias=1

[MeterTextColor3a]
Meter=String
StringAlign=Center
FontFace=Segoe UI
FontColor=#Color3#
FontSize=12
X=260r
Y=0r
W=100
Text=#Color3#
AntiAlias=1
SolidColor=0,0,0,80
LeftMouseUpAction=["#@#Addons\RainRGB4.exe" "VarName=Color3" "FileName=#@#Variables.inc"][!Refresh *]
FinishAction=[!Refresh *]

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeterDay]
Meter=String
StringAlign=Left
FontFace=Segoe UI Light
FontColor=255,255,255
FontSize=10
X=20
Y=328
Text="Day"
AntiAlias=1

[MeterMonth]
Meter=String
StringAlign=Left
FontFace=Segoe UI Light
FontColor=255,255,255
FontSize=10
X=146
Y=328
Text="Month"
AntiAlias=1

[MeterYear]
Meter=String
StringAlign=Left
FontFace=Segoe UI Light
FontColor=255,255,255
FontSize=10
X=270
Y=328
Text="Year"
AntiAlias=1

[MeterEvent]
Meter=String
StringAlign=Left
FontFace=Segoe UI Light
FontColor=255,255,255
FontSize=10
X=20
Y=375
Text="Event"
AntiAlias=1

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeterDayCode]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontColor=255,255,255
FontSize=12
X=65
Y=350
Text=#Day#
AntiAlias=1
ToolTipText=Type Event "day" and press the "Enter" key to Apply changes.
LeftMouseUpAction=[!PluginBang "MeterDayInput ExecuteBatch 1"]

[MeterDayInput]
Measure=Plugin
Plugin=InputText.dll
StringAlign=Center
FontFace=Segoe UI Light
FontSize=12
X=22
Y=352
W=95
H=20
AntiAlias=1
FocusDismiss=1
Command1=[!WriteKeyValue Variables Day "$UserInput$""#@#Variables.inc"][!RainmeterRefreshApp]
DefaultValue="#Day#"

[MeterMonthCode]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontColor=255,255,255
FontSize=12
X=193
Y=350
Text=#Month#
AntiAlias=1
ToolTipText=Type Event "Month" and press the "Enter" key to Apply changes.
LeftMouseUpAction=[!PluginBang "MeterMonthInput ExecuteBatch 1"]

[MeterMonthInput]
Measure=Plugin
Plugin=InputText.dll
StringAlign=Center
FontFace=Segoe UI Light
FontSize=12
X=148
Y=352
W=95
H=20
AntiAlias=1
FocusDismiss=1
Command1=[!WriteKeyValue Variables Month "$UserInput$""#@#Variables.inc"][!RainmeterRefreshApp]
DefaultValue="#Month#"

[MeterYearCode]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontColor=255,255,255
FontSize=12
X=320
Y=350
Text=#Year#
AntiAlias=1
ToolTipText=Type event "Year" and press the "Enter" key to Apply changes.
LeftMouseUpAction=[!PluginBang "MeterYearInput ExecuteBatch 1"]

[MeterYearInput]
Measure=Plugin
Plugin=InputText.dll
StringAlign=Center
FontFace=Segoe UI Light
FontSize=12
X=273
Y=351
W=95
H=20
AntiAlias=1
FocusDismiss=1
Command1=[!WriteKeyValue Variables Year "$UserInput$""#@#Variables.inc"][!RainmeterRefreshApp]
DefaultValue="#Year#"

[MeterEventCode]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontColor=255,255,255
FontSize=12
X=193
Y=395
Text=#Event#
AntiAlias=1
ToolTipText=Type event "Name/Description" and press the "Enter" key to Apply changes.
LeftMouseUpAction=[!PluginBang "MeterEventInput ExecuteBatch 1"]

[MeterEventInput]
Measure=Plugin
Plugin=InputText.dll
StringAlign=Center
FontFace=Segoe UI Light
FontSize=12
X=22
Y=397
W=350
H=20
AntiAlias=1
FocusDismiss=1
Command1=[!WriteKeyValue Variables Event "$UserInput$""#@#Variables.inc"][!RainmeterRefreshApp]
DefaultValue="#Event#"

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeterMediaMonkeyButtonPassive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=11
FontColor=255,255,255
X=545
Y=95
Text=MediaMonkey
SolidColor=0,0,0,1
AntiAlias=1
MouseOverAction=[!ShowMeter MeterMediaMonkeyButtonActive][!HideMeter MeterMediaMonkeyButtonPassive][!Update]

[MeterMediaMonkeyButtonActive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=11
FontWeight=800
FontColor=18,160,230
X=r
Y=r
Text=MediaMonkey
SolidColor=0,0,0,1
AntiAlias=1
Hidden=1
MouseLeaveAction=[!ShowMeter MeterMediaMonkeyButtonPassive][!HideMeter MeterMediaMonkeyButtonActive][!Update]
LeftMouseDownAction=[!WriteKeyValue Variables Player MediaMonkey "#@#Variables.inc"][!Refresh *]

[MeteriTunesButtonPassive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=11
FontColor=255,255,255
X=r
Y=25r
Text=iTunes
SolidColor=0,0,0,1
AntiAlias=1
MouseOverAction=[!ShowMeter MeteriTunesButtonActive][!HideMeter MeteriTunesButtonPassive][!Update]

[MeteriTunesButtonActive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=11
FontWeight=800
FontColor=18,160,230
X=r
Y=r
Text=iTunes
SolidColor=0,0,0,1
AntiAlias=1
Hidden=1
MouseLeaveAction=[!ShowMeter MeteriTunesButtonPassive][!HideMeter MeteriTunesButtonActive][!Update]
LeftMouseDownAction=[!WriteKeyValue Variables Player iTunes "#@#Variables.inc"][!Refresh *]

[MeterWMPButtonPassive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=11
FontColor=255,255,255
X=r
Y=25r
Text=Windows Media Player
SolidColor=0,0,0,1
AntiAlias=1
MouseOverAction=[!ShowMeter MeterWMPButtonActive][!HideMeter MeterWMPButtonPassive][!Update]

[MeterWMPButtonActive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=11
FontWeight=800
FontColor=18,160,230
X=r
Y=r
Text=Windows Media Player
SolidColor=0,0,0,1
AntiAlias=1
Hidden=1
MouseLeaveAction=[!ShowMeter MeterWMPButtonPassive][!HideMeter MeterWMPButtonActive][!Update]
LeftMouseDownAction=[!WriteKeyValue Variables Player WMP "#@#Variables.inc"][!Refresh *]

[MeterWinampButtonPassive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=11
FontColor=255,255,255
X=r
Y=25r
Text=Winamp
SolidColor=0,0,0,1
AntiAlias=1
MouseOverAction=[!ShowMeter MeterWinampButtonActive][!HideMeter MeterWinampButtonPassive][!Update]

[MeterWinampButtonActive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=11
FontWeight=800
FontColor=18,160,230
X=r
Y=r
Text=Winamp
SolidColor=0,0,0,1
AntiAlias=1
Hidden=1
MouseLeaveAction=[!ShowMeter MeterWinampButtonPassive][!HideMeter MeterWinampButtonActive][!Update]
LeftMouseDownAction=[!WriteKeyValue Variables Player Winamp "#@#Variables.inc"][!Refresh *]

[MeterFoobar2000ButtonPassive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=11
FontColor=255,255,255
X=r
Y=25r
Text=Foobar2000
SolidColor=0,0,0,1
AntiAlias=1
MouseOverAction=[!ShowMeter MeterFoobar2000ButtonActive][!HideMeter MeterFoobar2000ButtonPassive][!Update]

[MeterFoobar2000ButtonActive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=11
FontWeight=800
FontColor=18,160,230
X=r
Y=r
Text=Foobar2000
SolidColor=0,0,0,1
AntiAlias=1
Hidden=1
MouseLeaveAction=[!ShowMeter MeterFoobar2000ButtonPassive][!HideMeter MeterFoobar2000ButtonActive][!Update]
LeftMouseDownAction=[!WriteKeyValue Variables Player CAD "#@#Variables.inc"][!Refresh *]

[MeterAIMPButtonPassive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=11
FontColor=255,255,255
X=r
Y=25r
Text=AIMP
SolidColor=0,0,0,1
AntiAlias=1
MouseOverAction=[!ShowMeter MeterAIMPButtonActive][!HideMeter MeterAIMPButtonPassive][!Update]

[MeterAIMPButtonActive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=11
FontWeight=800
FontColor=18,160,230
X=r
Y=r
Text=AIMP
SolidColor=0,0,0,1
AntiAlias=1
Hidden=1
MouseLeaveAction=[!ShowMeter MeterAIMPButtonPassive][!HideMeter MeterAIMPButtonActive][!Update]
LeftMouseDownAction=[!WriteKeyValue Variables Player AIMP "#@#Variables.inc"][!Refresh *]

[MeterMusicBeeButtonPassive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=11
FontColor=255,255,255
X=r
Y=25r
Text=MusicBee
SolidColor=0,0,0,1
AntiAlias=1
MouseOverAction=[!ShowMeter MeterMusicBeeButtonActive][!HideMeter MeterMusicBeeButtonPassive][!Update]

[MeterMusicBeeButtonActive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=11
FontWeight=800
FontColor=18,160,230
X=r
Y=r
Text=MusicBee
SolidColor=0,0,0,1
AntiAlias=1
Hidden=1
MouseLeaveAction=[!ShowMeter MeterMusicBeeButtonPassive][!HideMeter MeterMusicBeeButtonActive][!Update]
LeftMouseDownAction=[!WriteKeyValue Variables Player CAD "#@#Variables.inc"][!Refresh *]

;-------------------------------------------------------------
;-------------------------------------------------------------

[Meter24hPassive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=13
FontColor=255,255,255
X=475
Y=303
Text=24 h Clock
SolidColor=0,0,0,1
AntiAlias=1
MouseOverAction=[!ShowMeter Meter24hActive][!HideMeter Meter24hPassive][!Update]

[Meter24hActive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=13
FontWeight=800
FontColor=18,160,230
X=r
Y=r
Text=24 h Clock
SolidColor=0,0,0,1
AntiAlias=1
Hidden=1
LeftMouseUpAction=[!WriteKeyValue Variables Format "H" "#@#Variables.inc"][!WriteKeyValue Variables Hidden2 "1" "#@#Variables.inc"][!WriteKeyValue Variables Hidden "0" "#@#Variables.inc"][!ShowMeter Meter24hPassive][!HideMeter Meter24hActive][!Refresh *]
MouseLeaveAction=[!ShowMeter Meter24hPassive][!HideMeter Meter24hActive][!Update]

[Meter12hPassive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=13
FontColor=255,255,255
X=605
Y=0r
Text=12 h Clock
SolidColor=0,0,0,1
AntiAlias=1
MouseOverAction=[!ShowMeter Meter12hActive][!HideMeter Meter12hPassive][!Update]

[Meter12hActive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=13
FontWeight=800
FontColor=18,160,230
X=r
Y=r
Text=12 h Clock
SolidColor=0,0,0,1
AntiAlias=1
Hidden=1
LeftMouseUpAction=[!WriteKeyValue Variables Format "#I" "#@#Variables.inc"][!WriteKeyValue Variables Hidden2 "0" "#@#Variables.inc"][!WriteKeyValue Variables Hidden "1" "#@#Variables.inc"][!ShowMeter Meter12hPassive][!HideMeter Meter12hActive][!Refresh *]
MouseLeaveAction=[!ShowMeter Meter12hPassive][!HideMeter Meter12hActive][!Update]

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeterCelsiusPassive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=13
FontColor=255,255,255
X=475
Y=347
Text=Celsius
SolidColor=0,0,0,1
AntiAlias=1
MouseOverAction=[!ShowMeter MeterCelsiusActive][!HideMeter MeterCelsiusPassive][!Update]

[MeterCelsiusActive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=13
FontWeight=800
FontColor=18,160,230
X=r
Y=r
Text=Celsius
SolidColor=0,0,0,1
AntiAlias=1
Hidden=1
LeftMouseUpAction=[!WriteKeyValue Variables Unit "m" "#@#Variables.inc"][!ShowMeter MeterCelsiusPassive][!HideMeter MeterCelsiusActive][!Refresh *]
MouseLeaveAction=[!ShowMeter MeterCelsiusPassive][!HideMeter MeterCelsiusActive][!Update]

[MeterFahrenheitPassive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=13
FontColor=255,255,255
X=605
Y=0r
Text=Fahrenheit
SolidColor=0,0,0,1
AntiAlias=1
MouseOverAction=[!ShowMeter MeterFahrenheitActive][!HideMeter MeterFahrenheitPassive][!Update]

[MeterFahrenheitActive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=13
FontWeight=800
FontColor=18,160,230
X=r
Y=r
Text=Fahrenheit
SolidColor=0,0,0,1
AntiAlias=1
Hidden=1
LeftMouseUpAction=[!WriteKeyValue Variables Unit "f" "#@#Variables.inc"][!ShowMeter MeterFahrenheitPassive][!HideMeter MeterFahrenheitActive][!Refresh *]
MouseLeaveAction=[!ShowMeter MeterFahrenheitPassive][!HideMeter MeterFahrenheitActive][!Update]

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeterCloseButtonPassive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=13
FontColor=255,255,255
X=540
Y=392
Text=Close Settings
SolidColor=0,0,0,1
AntiAlias=1
MouseOverAction=[!ShowMeter MeterCloseButtonActive][!HideMeter MeterCloseButtonPassive][!Update]

[MeterCloseButtonActive]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontSize=13
FontWeight=800
FontColor=255,2,44
X=r
Y=r
Text=Close Settings
SolidColor=0,0,0,1
AntiAlias=1
Hidden=1
LeftMouseUpAction=[!DeactivateConfig "Sonder\Settings" "Settings.ini"][!ShowMeter MeterCloseButtonPassive][!HideMeter MeterCloseButtonActive][!Update]
MouseLeaveAction=[!ShowMeter MeterCloseButtonPassive][!HideMeter MeterCloseButtonActive][!Update]
