[Rainmeter]
Update=1000
Author=Connect-R
BackgroundMode=2
SolidColor=200,170,119,1
DynamicWindowSize=1
AccurateText=1
MouseScrollUpAction=[!SetVariable Scale "(#Scale#+#ScrollMouseIncrement#)"][!WriteKeyValue Variables Scale "(#Scale#+#ScrollMouseIncrement#)"][!Refresh]
MouseScrollDownAction=[!SetVariable Scale "(#Scale#-#ScrollMouseIncrement# < 0.2 ? 0.2 : #Scale#-#ScrollMouseIncrement#)"][!WriteKeyValue Variables Scale "(#Scale#-#ScrollMouseIncrement# < 0.2 ? 0.2 : #Scale#-#ScrollMouseIncrement#)"][!Refresh]
LeftMouseDoubleClickAction=!ToggleConfig "Sonder\Settings" "Settings.ini"

[Variables]
@include=#@#Variables.inc
@include2=#@#Language\Language.inc
Scale=0.5

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeasureTime]
Measure=Time
Format="%#Format#:%M"

[MeasureAMPM]
Measure=Time
Format="%p"

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeasureDay]
Measure=Time
Format=%A
Substitute=#Date#

[MeasureDate]
Measure=Time
Format=%#d

[MeasureMonth]
Measure=Time
Format=%B
Substitute=#Date#

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeterBackground]
Meter=Image
ImageName=#@#Clock bg.png
X=(0*#Scale#)
Y=(40*#Scale#)
W=(300*#Scale#)
AntiAlias=1
ImageTint=#Color1#
UpdateDivider=-1

[MeterLine]
Meter=Shape
X=(110*#Scale#)
Y=(185*#Scale#)
Shape=Rectangle 0,0,(80*#Scale#),(1*#Scale#) | Fill Color #Color1# | StrokeWidth 0 | Stroke Color #Color1#,0
UpdateDivider=-1

;-------------------------------------------------------------
;-------------------------------------------------------------

[Meter24h]
Meter=String
MeasureName=MeasureTime
StringAlign=Center
FontFace=Streamster
FontColor=#Color1#
FontSize=(18*#Scale#)
X=(150*#Scale#)
Y=(15*#Scale#)
Text="%1"
AntiAlias=1
Hidden=#Hidden#

[Meter12h]
Meter=String
MeasureName=MeasureTime
MeasureName2=MeasureAmPm
StringAlign=Center
FontFace=Streamster
FontColor=#Color1#
FontSize=(18*#Scale#)
X=(150*#Scale#)
Y=(15*#Scale#)
Text="%1%2"
InlinePattern="[MeasureAmPm]"
InlineSetting=Size | (8*#Scale#)
AntiAlias=1
Hidden=#Hidden2#
DynamicVariables=1

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeterDay]
Meter=String
MeasureName=MeasureDay
StringCase=Upper
StringAlign=Center
FontColor=#Color1#
FontFace=Big John
FontSize=(20*#Scale#)
X=(150*#Scale#)
Y=(60*#Scale#)
Text="%1"
AntiAlias=1

[MeterDate]
Meter=String
MeasureName=MeasureDate
MeasureName2=MeasureMonth
StringCase=Upper
StringAlign=Center
FontColor=#Color1#
FontFace=Open Sans Light
FontSize=(15*#Scale#)
X=(150*#Scale#)
Y=(140*#Scale#)
Text="%1 %2"
AntiAlias=1
